# SELECT USER_ID, COUNT(*) OVER () AS CNT
# FROM USER_INFO 
# WHERE YEAR(JOINED) = 2021;

# SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(ONLINE_SALE.USER_ID) AS PURCHASED_USERS, 
# FROM ONLINE_SALE
# WHERE USER_ID IN (
#     SELECT USER_ID
#     FROM USER_INFO 
#     WHERE YEAR(JOINED) = 2021
# )
# GROUP BY YEAR, MONTH;

# SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT O.USER_ID)/U.CNT, 1) AS PUCHASED_RATIO
# FROM ONLINE_SALE O
# LEFT OUTER JOIN (
#     SELECT USER_ID, COUNT(*) OVER () AS CNT
#     FROM USER_INFO 
#     WHERE YEAR(JOINED) = 2021
# ) U
# ON O.USER_ID = U.USER_ID
# GROUP BY YEAR, MONTH
# ORDER BY YEAR, MONTH;

SELECT YEAR(O.SALES_DATE) AS YEAR,
       MONTH(O.SALES_DATE) AS MONTH,
       COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS,
       ROUND(COUNT(DISTINCT O.USER_ID) / U.CNT, 1) AS PUCHASED_RATIO
FROM ONLINE_SALE O
JOIN (
    SELECT USER_ID, COUNT(*) OVER () AS CNT
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
) U
  ON O.USER_ID = U.USER_ID
GROUP BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE)
ORDER BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE);