-- 코드를 작성해주세요
WITH RECURSIVE GEN AS (
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, GENERATION+1 AS GENERATION
    FROM ECOLI_DATA E
    JOIN GEN G
    ON E.PARENT_ID = G.ID
)
SELECT COUNT(*) AS COUNT, GENERATION
FROM ECOLI_DATA E
JOIN GEN G
ON E.ID = G.ID AND E.ID NOT IN (
    SELECT PARENT_ID AS ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION;