-- 코드를 입력하세요


WITH RECURSIVE HOUR_TABLE AS (
    SELECT 0 AS HOUR
    
    UNION ALL
    
    SELECT HOUR+1 AS HOUR
    FROM HOUR_TABLE
    WHERE HOUR < 23
)
SELECT H.HOUR, IFNULL(COUNT, 0) AS COUNT
FROM (
    SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    WHERE HOUR(DATETIME) BETWEEN 0 AND 23
    GROUP BY HOUR(DATETIME)
    ORDER BY HOUR
) T
RIGHT OUTER JOIN HOUR_TABLE H
ON T.HOUR = H.HOUR;