SELECT USER_ID, NICKNAME, TOTAL_SALES
FROM USED_GOODS_USER U
JOIN (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS='DONE'
    GROUP BY WRITER_ID
) B
ON U.USER_ID = B.WRITER_ID AND B.TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;