SELECT I.ID, N.FISH_NAME, M.LENGTH
FROM FISH_INFO I
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) M
ON M.FISH_TYPE = I.FISH_TYPE AND M.LENGTH = I.LENGTH
JOIN FISH_NAME_INFO N
ON N.FISH_TYPE = I.FISH_TYPE
ORDER BY I.ID;