SELECT S.*, H.EMP_NAME, H.POSITION, H.EMAIL
FROM (
    SELECT SUM(SCORE) AS SCORE, EMP_NO
    FROM HR_GRADE
    GROUP BY EMP_NO
) S
JOIN HR_EMPLOYEES H
ON H.EMP_NO = S.EMP_NO
WHERE SCORE = (
    SELECT MAX(SCORE)
    FROM (
        SELECT EMP_NO, SUM(SCORE) AS SCORE
        FROM HR_GRADE
        GROUP BY EMP_NO
    ) S
);